### ISSUE TITLE
Looks interesting

### ISSUE THREAD

**Issue by tyeeman** [rytc/gssg#1]
Yes, it does. It will be nice to have the blog posts working. Will they have the tags feature?

**Comment by tyeeman** [comment]
Just built this and ran the exe. I got this error - 

```
g:\test\www\gssg>gssg init
2022/02/17 22:46:24 Failed to open config.yaml for this site
```
How do I create the config.yml file?

**Comment by tyeeman** [comment]
OK, I found your site's files and used config.yml from them. The files did build except there is no index.html in the public folder!

**Comment by rytc** [comment]
Yeah, right now all it does is create the directory structure. It would probably be a good idea to include sample content at some point.

**Comment by rytc** [comment]
Blog post support was added, also added basic files to the initialization command so a functioning site will exist out of the box.
